version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.11.4-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge